apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-portal-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-portal
  template:
    metadata:
      labels:
        app: student-portal
    spec:
      containers:
        - name: student-portal
          image: student-portal:v1
          ports:
            - containerPort: 5000

# minikube start
# minikube image load student-portal:v1
# kubectl apply -f deployment.yaml
# kubectl get deployments
# kubectl get pods -l app=student-portal
# kubectl logs <pod-name>
# kubectl get pods
